Frontend auth
PendolinoVoyager/smart-security-slupsk pull request #5
Opened 2024-11-28 12:13 UTC by Besp1N

2024-11-28 12:23 UTC, PendolinoVoyager requested changes
:(

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/api/devicesApi.ts
> +    try {
unnecessary try/catch. Nothing throws here, fetchSafe return error

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/api/devicesApi.ts
> +        const response = await fetchSafe<{ id: string }[]>(`${API_URL}/api/v1/device/`, {
see authUtils and addCredentials to attach token

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/api/devicesApi.ts
> +        console.log(response);
remove this log

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/components/activation_acc/MainContainer.tsx
> +const MainContainer = () => (
bad naming too generic

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/components/pages/activationAccount.tsx
change the file and component name to ActivateAccountPage

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/components/pages/deviceDetails.tsx
same, change name to include page

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/components/pages/registerPage.tsx
If the only thing you show on a page is single component, make this component the page

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/components/pages/resetPassword.tsx
change name to include page

2024-11-28 12:23 UTC, PendolinoVoyager commented on sss-frontend/src/api/devicesApi.ts
> +    try {
nvm

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/api/devicesApi.ts
> +        const response = await fetchSafe<{ id: string }[]>(`${API_URL}/api/v1/device/`, {
done

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/api/devicesApi.ts
> +    try {
ok

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/api/devicesApi.ts
> +        console.log(response);
done

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/components/activation_acc/MainContainer.tsx
> +const MainContainer = () => (
Refactored

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/components/pages/activationAccount.tsx
done

2024-12-01 18:54 UTC, Besp1N commented on sss-frontend/src/components/pages/deviceDetails.tsx
yes sir!

2024-12-01 18:55 UTC, Besp1N commented on sss-frontend/src/components/pages/registerPage.tsx
done

2024-12-01 18:55 UTC, Besp1N commented on sss-frontend/src/components/pages/resetPassword.tsx
done!

2024-12-01 18:56 UTC, Besp1N reviewed
Done!

2024-12-01 18:57 UTC, PendolinoVoyager commented
LGTM

2024-12-01 18:58 UTC, merged